server:
  port: 8400
spring:
  application:
    name: timeslot
  datasource:
    username: 'sa'
    password:
    url: jdbc:h2:./data/timeslot
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  h2:
    console:
      enabled: true
      path: '/h2-console'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true